<?xml version="1.0" encoding="UTF-8"?>

    <xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:template match="/">
        <html xmlns="http://www.w3.org/1999/xhtml">
                <head>
                    <title>Pricing Packages for our photography | Rings &amp; Kisses </title>
                    <meta charset="UTF-8"/>
                    <meta name="viewport" content="width=device-width, initial-scale=1"/>
                    <link rel="stylesheet" href="style/style.css"/>
                    <link rel="preconnect" href="https://fonts.gstatic.com"/>
                    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
                    <link href="https://fonts.googleapis.com/css2?family=Dorsa&amp;family=Satisfy&amp;display=swap" rel="stylesheet"/>
                    <script type="text/javascript" src="scripts/script.js"/>
                    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
                    <script type="application/ld+json">
                        [ {
                        "@context" : "http://schema.org",
                        "@type" : "Product",
                        "name" : "Bronze",
                        "description" : "Wedding photography session with 8 hours of accompaniment. Images are delivered in an online gallery including a download link. You will also receive 15 printed photos in a photo box",
                        "brand" : {
                        "@type" : "Brand",
                        "name" : "RINGS &amp; KISSES",
                        "logo" : "https://it-craftsman.github.io/ringsandkisses/images/logo.svg"
                        },
                        "offers" : {
                        "@type" : "Offer",
                        "price" : "1990,00"
                        }
                        }, {
                        "@context" : "http://schema.org",
                        "@type" : "Product",
                        "name" : "Silver",
                        "description" : "Wedding photography session with 10 hours of accompaniment. Images are delivered in an online gallery including a download link. You will also receive 20 printed photos in a photo box.",
                        "brand" : {
                        "@type" : "Brand",
                        "name" : "RINGS &amp; KISSES",
                        "logo" : "https://it-craftsman.github.io/ringsandkisses/images/logo.svg"
                        },
                        "offers" : {
                        "@type" : "Offer",
                        "price" : "2290,00"
                        }
                        }, {
                        "@context" : "http://schema.org",
                        "@type" : "Product",
                        "name" : "Gold",
                        "description" : "Wedding photography session with 12 hours of accompaniment. Images are delivered in an online gallery including a download link. You will also receive 25 printed photos in a photo box.",
                        "brand" : {
                        "@type" : "Brand",
                        "name" : "RINGS &amp; KISSES",
                        "logo" : "https://it-craftsman.github.io/ringsandkisses/images/logo.svg"
                        },
                        "offers" : {
                        "@type" : "Offer",
                        "price" : "2290,00"
                        }
                        }, {
                        "@context" : "http://schema.org",
                        "@type" : "Product",
                        "name" : "Copper",
                        "description" : "Wedding photography session with 4 hours of accompaniment. Images are delivered in an online gallery including a download link.",
                        "brand" : {
                        "@type" : "Brand",
                        "name" : "RINGS &amp; KISSES",
                        "logo" : "https://it-craftsman.github.io/ringsandkisses/images/logo.svg"
                        },
                        "offers" : {
                        "@type" : "Offer",
                        "price" : "890,00"
                        }
                        }, {
                        "@context" : "http://schema.org",
                        "@type" : "Product",
                        "name" : "Basic",
                        "description" : "Couple photography session with one hour of shooting time. Images are delivered in an online gallery including a download link.",
                        "brand" : {
                        "@type" : "Brand",
                        "name" : "RINGS &amp; KISSES",
                        "logo" : "https://it-craftsman.github.io/ringsandkisses/images/logo.svg"
                        },
                        "offers" : {
                        "@type" : "Offer",
                        "price" : "340,00"
                        }
                        }, {
                        "@context" : "http://schema.org",
                        "@type" : "Product",
                        "name" : "Advanced",
                        "description" : "Couple photography session with one and a half hours of shooting time. Images are delivered in an online gallery including a download link.",
                        "brand" : {
                        "@type" : "Brand",
                        "name" : "RINGS &amp; KISSES",
                        "logo" : "https://it-craftsman.github.io/ringsandkisses/images/logo.svg"
                        },
                        "offers" : {
                        "@type" : "Offer",
                        "price" : "340,00"
                        }
                        } ]
                    </script>
                    <!-- Favicon -->
                    <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png"/>
                    <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png"/>
                    <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png"/>
                    <link rel="manifest" href="site.webmanifest"/>
                    <meta name="msapplication-TileColor" content="#da532c"/>
                    <meta name="theme-color" content="#ffffff"/>
                </head>
            <body>
                <header>
                    <nav id="nav" role="navigation">
                        <ul class="top-nav" id="top-nav">
                            <li><a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="myFunction()">&#9776;</a></li>
                            <li><a href="index.html">Home</a></li>
                            <li><a href="blog.html">Blog</a></li>
                            <li><a href="#" aria-haspopup="true">Portfolio</a>
                                <ul class="dropdown">
                                    <li><a href="wedding.html">Wedding Photography</a></li>
                                    <li><a href="couple.html">Couples Photography</a></li>
                                </ul>
                            </li>
                            <li><a href="couple.html" aria-haspopup="true">Info</a>
                                <ul class="dropdown">
                                    <li><a href="about.html">About Us</a></li>
                                    <li><a href="pricing.xhtml">Pricing</a></li>
                                </ul>
                            </li>
                            <li><a href="#" aria-haspopup="true">Contact</a>
                                <ul class="dropdown" aria-label="submenu">
                                    <li><a href="inquiry.html">Inquiry</a></li>
                                    <li><a href="imprint.html">Imprint</a></li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                    <div class="banner">
                        <img src="images/logo.svg" alt="ringsandkisses logo" width="120" height="90"/>
                        <h1>RINGS &amp; KISSES</h1>
                        <h2>Photography</h2>
                    </div>
                </header>
				  <ul class="breadcrumb">
					<li><a href="index.html">Home</a></li>
					<li>Pricing</li>
				  </ul> 
                <main>
                    <div class="about">
                        <h2>Pricing for couple and wedding photography</h2>
                        <p>Our unique price-performance ratio has made our customers happy for a long time and determines you too. </p>
                        <p>Trust in our reliability, quality and uniqueness.</p>
                    </div>
                    <div class="pricing-box-container">
                        <xsl:for-each select="sessions/session">
                            <div class="pricing-box text-center">
                                <h5><xsl:value-of select="type"/></h5>
                                <h6><xsl:value-of select="title"/></h6>
                                <p><xsl:value-of select="description"/></p>
                                <p class="price"><xsl:value-of select="price"/></p>
                            </div>
                        </xsl:for-each>
                    </div>
                </main>

<footer>
    <h3 id="text3" >Follow me on Instagram</h3>
    <div class="responsive">
        <div class="gallery">
            <img src="images/gallery/TF-web-DSC07641.jpg" alt="Romance between newly married couple" width="600" height="400"/>
        </div>
    </div>

    <div class="responsive">
        <div class="gallery">
            <img src="images/gallery/post05-1.jpg" alt="Groom is holding a bride and kisses on a beach" width="600" height="400"/>
        </div>
    </div>

    <div class="responsive">
        <div class="gallery">
            <img src="images/gallery/post11.jpg" alt="Photograph of a couple sitting on stage to recieve greetings from guests" width="600" height="400"/>
        </div>
    </div>

    <div class="responsive">
        <div class="gallery">
            <img src="images/gallery/TF-web-DSC07487.jpg" alt="Photograph of a newly married couple standing on a beach with flowers in grooms hand " width="600" height="400"/>
        </div>
    </div>
    <div class="clearfix"></div>
        <p>
            <a class="fa fa-facebook"></a>
            <a class="fa fa-pinterest"></a>
            <a class="fa fa-instagram"></a>
        </p>
		<div class="copyright">
 <a href="privacy.html">@copyright 2020 Rings&amp;Kisses</a>
</div>
</footer>
            </body>
        </html>
    </xsl:template>

</xsl:stylesheet>